### ISSUE TITLE
Collecting stats should be opt-in

### ISSUE THREAD

**Issue by edewit** [pie-flavor/Pieconomy#12]
Stats collection is now on per default, but in accordance with [this doc](https://docs.spongepowered.org/stable/en/plugin/metrics.html), it should be opt-in

**Comment by pie-flavor** [comment]
and it already is.
https://github.com/pie-flavor/Pieconomy/commit/0e8bd76938b3343d68ff776c1cae6232137d9080

**Comment by edewit** [comment]
Ahh right, thanks
