### ISSUE TITLE
1.10 Compatibility

### ISSUE THREAD

**Issue by Magi1053** [pie-flavor/Pieconomy#5]
I see that this plugin requires Sponge API 6. I tried using Sponge API 6 for 1.10,2, but it does not include the class TypeTokens, which this plugin uses. Please support Sponge API 5 (Stable) for 1.10

**Comment by pie-flavor** [comment]
I do not understand what is meant by "Sponge API 6 for 1.10.2"; I was under the impression that API 6 was only for 1.11.
I cannot support API 5 because it does not have the inventory API support that this plugin needs.

**Comment by Magi1053** [comment]
There is an experimental build of API 6 for 1.10 that does not include the class I mentioned above

**Comment by pie-flavor** [comment]
I generally don't update my plugins to unstable releases of things, and it's not an API restriction but an implementation restriction.
