### ISSUE TITLE
after adding custom currency mod doesn't even load 

### ISSUE THREAD

**Issue by TheOhana** [pie-flavor/Pieconomy#7]
Hi i have a little problem first of all after istalling your plugin the first time all works fine, but after trying to add custom currencys the mod doesn't even load up for me if i try to use the commands it just says there is no such command i wonder why? dou you know a fix for this or even noticed this issue

**Comment by pie-flavor** [comment]
Well if it didn't load, then you most likely added the currencies incorrectly. Please post your config.

**Comment by TheOhana** [comment]
items {

  "minecraft:gold_nugget" {

    currency = gold

    amount = 1

  }

  "minecraft:gold_ingot" {

    currency = gold

    amount = 9

  }

  "minecraft:gold_block" {

    currency = gold

    amount = 81

  }
  
  "minecraft:emerald" {
  
	currency = emerald
	
	amount = 1
	
  }
  
  "minecraft:emerald_block"
  
  currency = emerald
  
  amount = 1
  
  }

}



currencies {

  gold {

    decimal-places = 0

    name = {text = Gold}

    plural = {text = Gold}

    symbol = {text = G, color = gold}

    format = {text = "%{amount}% %{symbol}%"}

    exchangeable = true

  }
  
  emerald {

    decimal-places = 0

    name = {text = Emerald}

    plural = {text = Emeralds}

    symbol = {text = E, color = green}

    format = {text = "%{amount}% %{symbol}%"}

    exchangeable = true

  }

}



default-currency = gold



server-accounts {

  enable = true

  autosave-interval = 20

  accounts = 

    {

      id = "bank"

      name = "Bank"

      currencies {

        values = []

        type = blacklist

      }

      negative-values {

        values = []

        type = whitelist

      }

    }

  ]

  dynamic-accounts {

    enable = false

    currencies {

      values = []

      type = blacklist

    }

    negative-values {

      values = []

      type = whitelist

    }

  }

}



version = 3

**Comment by TheOhana** [comment]
here it is but it seems everything alright ?! https://gist.github.com/TheOhana/9903921462285316dcf3d44e19aa660f

**Comment by TheOhana** [comment]
it has to do with FMLPostInitializationEvent

**Comment by pie-flavor** [comment]
Please post your updated config in a gist.
