### ISSUE TITLE
still got the issue of not loading

### ISSUE THREAD

**Issue by TheOhana** [pie-flavor/Pieconomy#8]
after fixing my dumb mistake
it also didnt load up
its at line 61/62 https://gist.github.com/TheOhana/825790a7d71e06b328178ca494bd6f73

**Comment by pie-flavor** [comment]
As I said in the other issue, please post your updated config via a gist.

**Comment by TheOhana** [comment]
Here it is.
https://gist.github.com/TheOhana/6ceed5a01824b69d76d34867cb9b0c18

**Comment by pie-flavor** [comment]
You have deleted the initial `[` from `accounts =`. The line should read `accounts = [`.

**Comment by TheOhana** [comment]
i checked your default config and there wasnt an [ after accounts = either, so maybe look it up for yourself because i am 100 % sure i didnt touch this file by now. just a hint it's not my pebkac.

**Comment by pie-flavor** [comment]
False.
https://github.com/pie-flavor/Pieconomy/blob/master/src/main/resources/assets/pieconomy/default.conf#L32
And checking in the JAR, downloaded directly from Ore:
![](https://i.imgur.com/FUuM5Ya.png)
And from the Ore page:
![](https://i.imgur.com/K6OFdt0.png)
